import { motion } from "framer-motion";

const stats = [
  { value: "$127M+", description: "Revenue generated by our students" },
  { value: "9,500+", description: "Successful stores launched" },
  { value: "25+", description: "Hours of video content" },
];

export default function StatsBanner() {
  return (
    <section className="bg-primary py-8 text-white">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
          {stats.map((stat, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 * index, duration: 0.5 }}
            >
              <p className="text-4xl font-bold">{stat.value}</p>
              <p className="text-lg mt-1 opacity-90">{stat.description}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
